# -*- coding: utf-8 -*-
"""Infection Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueEF8sysKFrQkmH0T7Hcwamyqf4fjtIX
"""

import random
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact, IntSlider, FloatSlider

def infect_people(population_size, infection_prob, start_infected):
  days_infected = [0] * population_size
  infected_counts = []
  recovery_days = 10


  population = ['S'] * population_size
  for i in range(start_infected):
    population[i] = "I"
  days = 30
  infection_prob = 0.05
  for day in range(days):
      new_population = population.copy()
      for i, person in enumerate(population):
          if person == "I":
              for _ in range(5):
                  j = random.randint(0, 99)
                  if population[j] == "S" and random.random() < infection_prob:
                      new_population[j] = "I"
              days_infected[i] += 1
              if days_infected[i] >= recovery_days:
                  new_population[i] = "R"
      population = new_population
      infected_counts.append(population.count("I"))

  plt.plot(infected_counts)
  plt.title("Infected People Over Time")
  plt.xlabel("Day")
  plt.ylabel("Number Infected")
  plt.show()

interact(infect_people, population_size = IntSlider(min = 100, max = 1000, step = 100)
, infection_prob = FloatSlider(min = 0.01, max = 0.99, step = 0.01),
         start_infected = IntSlider(min = 1, max = 100, step = 1))