# -*- coding: utf-8 -*-
"""Infection Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueEF8sysKFrQkmH0T7Hcwamyqf4fjtIX
"""

import streamlit as st
import random
import matplotlib.pyplot as plt


st.title("Stochastic Disease Spread Simulation")


population_size = st.slider("Population Size", 100, 1000, step=100)
infection_prob = st.slider("Infection Probability", 0.01, 0.99, 0.01)
start_infected = st.slider("Initial Infected", 1, 100, 5)


def infect_people(population_size, infection_prob, start_infected):
    days_infected = [0] * population_size
    infected_counts = []
    recovery_days = 10
    population = ['S'] * population_size

    for i in range(start_infected):
        population[i] = "I"

    days = 30
    for day in range(days):
        new_population = population.copy()
        for i, person in enumerate(population):
            if person == "I":
                for _ in range(5):  # Interactions per infected person
                    j = random.randint(0, population_size - 1)
                    if population[j] == "S" and random.random() < infection_prob:
                        new_population[j] = "I"
                days_infected[i] += 1
                if days_infected[i] >= recovery_days:
                    new_population[i] = "R"
        population = new_population
        infected_counts.append(population.count("I"))

    return infected_counts


infected_counts = infect_people(population_size, infection_prob, start_infected)


fig, ax = plt.subplots()
ax.plot(infected_counts)
ax.set_title("Infected People Over Time")
ax.set_xlabel("Day")
ax.set_ylabel("Number Infected")
st.pyplot(fig)